name: build

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: npm
      - run: npm ci
      - run: npm run pretest
